"""ip address test revert

Revision ID: 35ce1f7c29fe
Revises: f22f86c4060a
Create Date: 2022-03-25 11:54:13.543445

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ce1f7c29fe'
down_revision = 'f22f86c4060a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ip_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_address', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
